// https://food-boutique.b.goit.study/api/products/discount

const discountProducts = [
  {
    _id: "640c2dd963a319ea671e366d",
    name: "Beef Fillet",
    desc: "Beef is the culinary name for meat from cattle, particularly skeletal muscle. Humans have been eating beef since prehistoric times. Beef is a source of high-quality protein and nutrients.\r\n\r\nMost beef skeletal muscle meat can be used as is by merely cutting into certain parts, such as roasts, short ribs or steak (filet mignon, sirloin steak, rump steak, rib steak, rib eye steak, hanger steak, etc.), while other cuts are processed (corned beef or beef jerky). Trimmings, on the other hand, are usually mixed with meat from older, leaner (therefore tougher) cattle, are ground, minced or used in sausages. The blood is used in some varieties called blood sausage. Other parts that are eaten include other muscles and offal, such as the oxtail, liver, tongue, tripe from the reticulum or rumen, glands (particularly the pancreas and thymus, referred to as sweetbread), the heart, the brain (although forbidden where there is a danger of bovine spongiform encephalopathy, BSE, commonly referred to as mad cow disease), the kidneys, and the tender testicles of the bull (known in the United States as calf fries, prairie oysters, or Rocky Mountain oysters). Some intestines are cooked and eaten as is, but are more often cleaned and used as natural sausage casings. The bones are used for making beef stock.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e366d.png",
    price: 29.99,
    size: "1 lb",
    category: "Meat_&_Seafood",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 308,
  },
  {
    _id: "640c2dd963a319ea671e366e",
    name: "Beef Gravy",
    desc: "Beef is the culinary name for meat from cattle, particularly skeletal muscle. Humans have been eating beef since prehistoric times. Beef is a source of high-quality protein and nutrients.\r\n\r\nMost beef skeletal muscle meat can be used as is by merely cutting into certain parts, such as roasts, short ribs or steak (filet mignon, sirloin steak, rump steak, rib steak, rib eye steak, hanger steak, etc.), while other cuts are processed (corned beef or beef jerky). Trimmings, on the other hand, are usually mixed with meat from older, leaner (therefore tougher) cattle, are ground, minced or used in sausages. The blood is used in some varieties called blood sausage. Other parts that are eaten include other muscles and offal, such as the oxtail, liver, tongue, tripe from the reticulum or rumen, glands (particularly the pancreas and thymus, referred to as sweetbread), the heart, the brain (although forbidden where there is a danger of bovine spongiform encephalopathy, BSE, commonly referred to as mad cow disease), the kidneys, and the tender testicles of the bull (known in the United States as calf fries, prairie oysters, or Rocky Mountain oysters). Some intestines are cooked and eaten as is, but are more often cleaned and used as natural sausage casings. The bones are used for making beef stock.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e366e.png",
    price: 4.99,
    size: "16 oz",
    category: "Pantry_Items",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 78,
  },
  {
    _id: "640c2dd963a319ea671e365f",
    name: "Avocado",
    desc: "The avocado, a tree with probable origin in South Central Mexico, is classified as a member of the flowering plant family Lauraceae. The fruit of the plant, also called an avocado (or avocado pear or alligator pear), is botanically a large berry containing a single large seed.\r\n\r\nAvocados are commercially valuable and are cultivated in tropical and Mediterranean climates throughout the world. They have a green-skinned, fleshy body that may be pear-shaped, egg-shaped, or spherical. Commercially, they ripen after harvesting. Avocado trees are partially self-pollinating, and are often propagated through grafting to maintain predictable fruit quality and quantity. In 2017, Mexico produced 34% of the world supply of avocados.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e365f.png",
    price: 1.99,
    size: "Each",
    category: "Fresh_Produce",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 140,
  },
  {
    _id: "640c2dd963a319ea671e365e",
    name: "Pork",
    desc: "Pork is the culinary name for the flesh of a domestic pig (Sus scrofa domesticus). It is the most commonly consumed meat worldwide,[1] with evidence of pig husbandry dating back to 5000 BC.\r\n\r\nPork is eaten both freshly cooked and preserved. Curing extends the shelf life of the pork products. Ham, smoked pork, gammon, bacon and sausage are examples of preserved pork. Charcuterie is the branch of cooking devoted to prepared meat products, many from pork.\r\n\r\nPig is the most popular meat in the Eastern and non-Muslim parts of Southeastern Asia (Indochina, Philippines, Singapore, East Timor) and is also very common in the Western world, especially in Central Europe. It is highly prized in Asian cuisines for its fat content and pleasant texture. Consumption of pork is forbidden by Jewish, Muslim and Rastafarian dietary law, for religious reasons, with several suggested possible causes.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e365e.png",
    price: 5.99,
    size: "1 lb",
    category: "Meat_&_Seafood",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 16,
  },
  {
    _id: "640c2dd963a319ea671e3671",
    name: "Biryani Masala",
    desc: "Biryani, also known as biriyani, biriani, birani or briyani, is a mixed rice dish with its origins among the Muslims of the Indian subcontinent. It can be compared to mixing a curry, later combining it with semi-cooked rice separately. This dish is especially popular throughout the Indian subcontinent, as well as among the diaspora from the region. It is also prepared in other regions such as Iraqi Kurdistan. It is made with Indian spices, rice, meat (chicken, goat, beef, lamb, prawn, or fish), vegetables or eggs.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e3671.png",
    price: 3.99,
    size: "100g",
    category: "Pantry_Items",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 34,
  },
  {
    _id: "640c2dd963a319ea671e3672",
    name: "Black Pepper",
    desc: "Black pepper (Piper nigrum) is a flowering vine in the family Piperaceae, cultivated for its fruit, known as a peppercorn, which is usually dried and used as a spice and seasoning. When fresh and fully mature, it is about 5 mm (0.20 in) in diameter and dark red, and contains a single seed, like all drupes. Peppercorns and the ground pepper derived from them may be described simply as pepper, or more precisely as black pepper (cooked and dried unripe fruit), green pepper (dried unripe fruit), or white pepper (ripe fruit seeds).\r\n\r\nBlack pepper is native to present-day Kerala in Southwestern India, and is extensively cultivated there and elsewhere in tropical regions. Vietnam is the world's largest producer and exporter of pepper, producing 34% of the world's crop, as of 2013.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e3672.png",
    price: 2.99,
    size: "100g",
    category: "Pantry_Items",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 20,
  },
  {
    _id: "640c2dd963a319ea671e3673",
    name: "Black Treacle",
    desc: 'Molasses (American English) or black treacle (British English) is a viscous product resulting from refining sugarcane or sugar beets into sugar. Molasses varies by amount of sugar, method of extraction, and age of plant. Sugarcane molasses is primarily used for sweetening and flavoring foods in the United States, Canada, and elsewhere. Molasses is a defining component of fine commercial brown sugar.\r\n\r\nSweet sorghum syrup may be colloquially called "sorghum molasses" in the southern United States.[2][3] Similar products include honey, maple syrup, corn syrup, and invert syrup. Most of these alternative syrups have milder flavors.',
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e3673.png",
    price: 4.99,
    size: "16 oz",
    category: "Pantry_Items",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 8,
  },
  {
    _id: "640c2dd963a319ea671e3674",
    name: "Borlotti Beans",
    desc: "A type of bean, also known as cranberry beans, with a creamy texture and a nutty flavor that is often used in Italian cuisine.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e3674.png",
    price: 1.29,
    size: "1 lb",
    category: "Pantry_Items",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 14,
  },
  {
    _id: "640c2dd963a319ea671e3676",
    name: "Bramley Apples",
    desc: "A type of apple that is popular in the UK and Ireland, known for its tart flavor and firm texture, which makes it ideal for cooking and baking.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e3676.png",
    category: "Fresh_Produce",
    price: 2.99,
    size: "1lb",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 6515,
  },
  {
    _id: "640c2dd963a319ea671e3675",
    name: "Bowtie Pasta",
    desc: "A type of pasta with a distinctive bowtie or butterfly shape that is often used in pasta salads and other cold dishes.",
    img: "https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e3675.png",
    category: "Pantry_Items",
    price: 1.99,
    size: "16oz",
    is10PercentOff: true,
    updatedAt: "2023-12-05T01:01:18.025Z",
    popularity: 5,
  },
];
