import './js/additional-features/scroll-up-btn';
import './js/commons';
import './js/api-servise/api-service-basic';
import './js/helpers/loaders';
import './js/footer';
import './js/modals';
import './js/cart-page-js/cart-js';
import './js/cart-page-js/cart-order-list'
import './js/cart-page-js/cart-total'
